spring:
  application:
    name: max-integer-solver
    title: max-integer-solver
  h2:
    console:
      enabled: true
  datasource:
    url: ${DATABASE_URL}
    driverClassName: "org.h2.Driver"
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: /max-integer-solver

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
